- hosts: 127.0.0.1 
  strategy: debug
  tasks: 
    - name: "wait for website to come up"
      uri:
        url: "http://localhost:8079"
        status_code: 200
      register: result
      #until: result.status == 204
      #retry: 1
      #delay: 10
      no_log: false
      ignore_errors: yes
    - name: run when success
      shell: echo {{ result }}
      register: tmp
      when: result.status== 200
    - name: run when failed
      shell: echo "fail"
      register: f
      when: result.failed
    - debug:
        var: tmp.stdout
    - name: send notification to Teams channel
      uri: 
        url: "webhook url"
        method: POST
        body_format: json
        body:
          title: "Daily Health Check"
          text: {{ tmp.stdout }}
          sections:
            - facts:
                - name: "{{ component_x  }}"
                  value: "{{ tmp.stdout  }}"
                - name: "{{ abc  }}"
                  value: "{{ xyz  }}"
